/* The following code was generated by JFlex 1.4.3 on 6/17/13 4:27 PM */

import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/17/13 4:27 PM from the specification file
 * <tt>lcalc.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\11\1\0\1\12\1\10\22\0\1\12\1\33\1\60"+
    "\2\0\1\25\1\0\1\7\1\13\1\15\1\14\1\23\1\22\1\24"+
    "\1\4\1\16\4\61\6\2\1\21\1\20\1\32\1\31\1\30\2\0"+
    "\32\1\1\26\1\17\1\27\1\0\1\3\1\0\1\40\1\56\1\45"+
    "\1\55\1\52\1\42\1\37\1\54\1\47\2\1\1\6\1\41\1\44"+
    "\1\36\1\34\1\1\1\35\1\51\1\46\1\43\1\50\1\53\1\1"+
    "\1\57\1\1\1\0\1\5\1\0\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\0\1\2\1\3\1\1\1\4\1\5\1\2"+
    "\2\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\17\3\1\27\1\30\2\31\1\32\1\33\1\34"+
    "\2\0\1\35\1\36\1\37\1\40\1\41\2\3\1\42"+
    "\1\43\11\3\1\44\2\3\1\45\10\3\1\46\2\3"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\32\1\57\2\0\2\35\3\3\1\60\3\3\1\61"+
    "\1\3\1\62\7\3\1\63\1\3\1\64\2\3\1\65"+
    "\4\3\1\0\1\35\12\3\1\66\1\67\1\70\1\71"+
    "\1\72\1\3\1\73\2\3\1\74\6\3\1\75\1\76"+
    "\1\3\1\77\1\100\2\3\1\101\1\102\1\3\1\103"+
    "\1\104\1\105\1\106\1\3\1\107\1\3\1\110\1\3"+
    "\1\111\1\112";

  private static int [] zzUnpackAction() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\144\0\u012c"+
    "\0\u015e\0\144\0\u0190\0\144\0\144\0\u01c2\0\144\0\u01f4"+
    "\0\144\0\144\0\144\0\144\0\144\0\144\0\u0226\0\144"+
    "\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6"+
    "\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514\0\u0546"+
    "\0\u0578\0\144\0\u05aa\0\u05dc\0\144\0\u060e\0\144\0\372"+
    "\0\u0640\0\u0672\0\u06a4\0\144\0\144\0\144\0\144\0\u06d6"+
    "\0\u0708\0\226\0\226\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802"+
    "\0\u0834\0\u0866\0\u0898\0\u08ca\0\226\0\u08fc\0\u092e\0\226"+
    "\0\u0960\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe"+
    "\0\226\0\u0af0\0\u0b22\0\144\0\144\0\144\0\144\0\144"+
    "\0\144\0\144\0\144\0\144\0\144\0\u0b54\0\u0b86\0\u0bb8"+
    "\0\144\0\u0bea\0\u0c1c\0\u0c4e\0\226\0\u0c80\0\u0cb2\0\u0ce4"+
    "\0\226\0\u0d16\0\226\0\u0d48\0\u0d7a\0\u0dac\0\u0dde\0\u0e10"+
    "\0\u0e42\0\u0e74\0\226\0\u0ea6\0\226\0\u0ed8\0\u0f0a\0\226"+
    "\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\u1004\0\u0b54\0\u1036\0\u1068"+
    "\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6\0\u11f8"+
    "\0\226\0\226\0\226\0\226\0\226\0\u122a\0\226\0\u125c"+
    "\0\u128e\0\226\0\u12c0\0\u12f2\0\u1324\0\u1356\0\u1388\0\u13ba"+
    "\0\226\0\226\0\u13ec\0\226\0\226\0\u141e\0\u1450\0\226"+
    "\0\226\0\u1482\0\226\0\226\0\226\0\226\0\u14b4\0\226"+
    "\0\u14e6\0\226\0\u1518\0\226\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\7\1\4\1\10"+
    "\1\11\2\12\1\13\1\14\1\15\1\16\1\3\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\4\1\36"+
    "\1\4\1\37\1\40\1\4\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\4\1\50\1\51\1\4\1\52"+
    "\1\5\10\53\1\54\1\55\5\53\1\56\40\53\1\57"+
    "\1\53\63\0\3\4\2\0\1\4\25\0\24\4\1\0"+
    "\1\4\2\0\1\5\1\0\1\60\54\0\1\5\2\0"+
    "\1\60\56\0\1\60\1\0\2\61\3\0\1\61\25\0"+
    "\24\61\1\0\1\61\11\0\1\12\64\0\1\62\63\0"+
    "\1\63\74\0\1\64\61\0\1\65\61\0\1\66\61\0"+
    "\1\67\31\0\3\4\2\0\1\4\25\0\1\4\1\70"+
    "\22\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\16\4\1\71\5\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\4\25\0\1\4\1\72\4\4\1\73\15\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\1\4\1\74"+
    "\6\4\1\75\13\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\76\25\0\2\4\1\77\4\4\1\100\14\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\10\4\1\101"+
    "\13\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\2\4\1\102\1\4\1\103\13\4\1\104\3\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\2\4\1\105"+
    "\15\4\1\106\2\4\1\107\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\6\4\1\110\1\4\1\111\13\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\2\4"+
    "\1\112\1\4\1\113\17\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\12\4\1\114\11\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\115\25\0\10\4\1\116\13\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\1\4"+
    "\1\117\16\4\1\120\3\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\2\4\1\121\21\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\2\4\1\122\13\4"+
    "\1\123\5\4\1\0\1\4\10\53\2\0\5\53\1\0"+
    "\40\53\1\0\1\53\11\0\1\55\50\0\7\124\1\125"+
    "\1\124\1\0\5\124\1\126\15\124\1\127\4\124\1\130"+
    "\1\124\1\131\1\124\1\132\7\124\1\133\2\124\1\134"+
    "\7\0\1\135\52\0\14\136\1\137\45\136\10\63\1\140"+
    "\1\141\50\63\1\0\3\4\2\0\1\4\25\0\2\4"+
    "\1\142\21\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\1\143\3\4\1\144\1\4\1\145\2\4\1\146"+
    "\1\147\11\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\1\4\1\150\22\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\21\4\1\151\2\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\2\4\1\152\21\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\1\4"+
    "\1\153\22\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\10\4\1\154\13\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\12\4\1\155\11\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\10\4\1\156\13\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\15\4"+
    "\1\157\6\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\4\4\1\160\17\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\16\4\1\161\5\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\1\162\23\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\12\4\1\163"+
    "\11\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\13\4\1\164\10\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\4\25\0\1\4\1\165\22\4\1\0\1\4\1\0"+
    "\3\4\2\0\1\4\25\0\1\4\1\166\22\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\15\4\1\167"+
    "\6\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\21\4\1\170\2\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\4\25\0\13\4\1\171\10\4\1\0\1\4\1\0"+
    "\3\4\2\0\1\4\25\0\13\4\1\172\10\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\2\4\1\173"+
    "\21\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\3\4\1\174\20\4\1\0\1\4\14\136\1\175\60\136"+
    "\1\0\1\137\1\176\44\136\11\0\1\141\51\0\3\4"+
    "\2\0\1\4\25\0\3\4\1\177\20\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\16\4\1\200\5\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\21\4"+
    "\1\201\2\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\2\4\1\202\21\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\7\4\1\203\14\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\4\4\1\204\17\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\4\4"+
    "\1\205\17\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\11\4\1\206\12\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\13\4\1\207\10\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\15\4\1\210\6\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\16\4"+
    "\1\211\5\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\1\4\1\212\22\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\10\4\1\213\13\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\16\4\1\214\5\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\21\4"+
    "\1\215\2\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\13\4\1\216\10\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\16\4\1\217\5\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\12\4\1\220\11\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\221\25\0\24\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\222\25\0\24\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\13\4"+
    "\1\223\10\4\1\0\1\4\14\136\1\175\1\141\44\136"+
    "\1\0\3\4\2\0\1\4\25\0\1\4\1\224\22\4"+
    "\1\0\1\4\1\0\3\4\2\0\1\4\25\0\4\4"+
    "\1\225\17\4\1\0\1\4\1\0\3\4\2\0\1\226"+
    "\25\0\24\4\1\0\1\4\1\0\3\4\2\0\1\4"+
    "\25\0\1\4\1\227\22\4\1\0\1\4\1\0\3\4"+
    "\2\0\1\4\25\0\1\4\1\230\22\4\1\0\1\4"+
    "\1\0\3\4\2\0\1\4\25\0\23\4\1\231\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\12\4\1\232"+
    "\11\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\12\4\1\233\11\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\234\25\0\24\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\4\25\0\12\4\1\235\11\4\1\0\1\4\1\0"+
    "\3\4\2\0\1\4\25\0\10\4\1\236\13\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\16\4\1\237"+
    "\5\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\16\4\1\240\5\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\4\25\0\10\4\1\241\13\4\1\0\1\4\1\0"+
    "\3\4\2\0\1\4\25\0\4\4\1\242\17\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\12\4\1\243"+
    "\11\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\10\4\1\244\13\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\4\25\0\21\4\1\245\2\4\1\0\1\4\1\0"+
    "\3\4\2\0\1\4\25\0\10\4\1\246\13\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\13\4\1\247"+
    "\10\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\3\4\1\250\20\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\251\25\0\24\4\1\0\1\4\1\0\3\4\2\0"+
    "\1\4\25\0\5\4\1\252\16\4\1\0\1\4\1\0"+
    "\3\4\2\0\1\4\25\0\2\4\1\253\21\4\1\0"+
    "\1\4\1\0\3\4\2\0\1\4\25\0\10\4\1\254"+
    "\13\4\1\0\1\4\1\0\3\4\2\0\1\4\25\0"+
    "\10\4\1\255\13\4\1\0\1\4";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5450];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\0\1\11\3\1\1\11\2\1\1\11\1\1"+
    "\2\11\1\1\1\11\1\1\6\11\1\1\1\11\21\1"+
    "\1\11\2\1\1\11\1\1\1\11\1\1\2\0\1\1"+
    "\4\11\34\1\12\11\2\0\1\1\1\11\33\1\1\0"+
    "\60\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
   
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 57: 
          { return symbol(sym.TYPE);
          }
        case 75: break;
        case 33: 
          { return symbol(sym.NOT_EQUAL);
          }
        case 76: break;
        case 16: 
          { return symbol(sym.MOD);
          }
        case 77: break;
        case 30: 
          { return symbol(sym.ASSIGN);
          }
        case 78: break;
        case 23: 
          { yybegin(STRING); string.setLength(0);
          }
        case 79: break;
        case 58: 
          { return symbol(sym.VOID);
          }
        case 80: break;
        case 34: 
          { return symbol(sym.OR);
          }
        case 81: break;
        case 21: 
          { return symbol(sym.LESS_THAN);
          }
        case 82: break;
        case 5: 
          { return symbol(sym.BOOLEAN_LITERAL, new Boolean(yytext()));
          }
        case 83: break;
        case 61: 
          { return symbol(sym.ARRAY);
          }
        case 84: break;
        case 62: 
          { return symbol(sym.FLOAT);
          }
        case 85: break;
        case 15: 
          { return symbol(sym.MINUS);
          }
        case 86: break;
        case 32: 
          { return symbol(sym.LESS_THAN_OR_EQUAL);
          }
        case 87: break;
        case 45: 
          { string.append( '\t' );
          }
        case 88: break;
        case 11: 
          { return symbol(sym.SEMICOLON);
          }
        case 89: break;
        case 59: 
          { return symbol(sym.ELSE);
          }
        case 90: break;
        case 20: 
          { return symbol(sym.EQUAL);
          }
        case 91: break;
        case 72: 
          { return symbol(sym.PROGRAM);
          }
        case 92: break;
        case 63: 
          { return symbol(sym.UNTIL);
          }
        case 93: break;
        case 4: 
          { return symbol(sym.DOT);
          }
        case 94: break;
        case 12: 
          { return symbol(sym.COLON);
          }
        case 95: break;
        case 51: 
          { return symbol(sym.INT);
          }
        case 96: break;
        case 49: 
          { return symbol(sym.AND);
          }
        case 97: break;
        case 26: 
          { char val = (char) Integer.parseInt(yytext().substring(1),8);
                        	   string.append( val );
          }
        case 98: break;
        case 44: 
          { string.append( '\n' );
          }
        case 99: break;
        case 37: 
          { return symbol(sym.IF);
          }
        case 100: break;
        case 19: 
          { return symbol(sym.GREATER_THAN);
          }
        case 101: break;
        case 1: 
          { return symbol(sym.INT_LITERAL, new Integer(yytext()));
          }
        case 102: break;
        case 36: 
          { return symbol(sym.TO);
          }
        case 103: break;
        case 22: 
          { return symbol(sym.NOT);
          }
        case 104: break;
        case 27: 
          { yybegin(YYINITIAL); return symbol(sym.STRING_LITERAL, string.toString());
          }
        case 105: break;
        case 73: 
          { return symbol(sym.WRITELN);
          }
        case 106: break;
        case 65: 
          { return symbol(sym.WHILE);
          }
        case 107: break;
        case 67: 
          { return symbol(sym.REPEAT);
          }
        case 108: break;
        case 13: 
          { return symbol(sym.SEMI);
          }
        case 109: break;
        case 69: 
          { return symbol(sym.RECORD);
          }
        case 110: break;
        case 35: 
          { return symbol(sym.OF);
          }
        case 111: break;
        case 71: 
          { return symbol(sym.STRING);
          }
        case 112: break;
        case 53: 
          { return symbol(sym.END);
          }
        case 113: break;
        case 39: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 114: break;
        case 14: 
          { return symbol(sym.PLUS);
          }
        case 115: break;
        case 52: 
          { return symbol(sym.VAR);
          }
        case 116: break;
        case 42: 
          { string.append( '\r' );
          }
        case 117: break;
        case 46: 
          { string.append( '\b' );
          }
        case 118: break;
        case 9: 
          { return symbol(sym.RPAR);
          }
        case 119: break;
        case 66: 
          { return symbol(sym.BEGIN);
          }
        case 120: break;
        case 25: 
          { throw new RuntimeException("Unterminated string at end of line");
          }
        case 121: break;
        case 56: 
          { return symbol(sym.THEN);
          }
        case 122: break;
        case 7: 
          { return symbol(sym.LPAR);
          }
        case 123: break;
        case 70: 
          { return symbol(sym.RETURN);
          }
        case 124: break;
        case 8: 
          { return symbol(sym.TIMES);
          }
        case 125: break;
        case 17: 
          { return symbol(sym.LBRACKET);
          }
        case 126: break;
        case 40: 
          { string.append( '\'' );
          }
        case 127: break;
        case 74: 
          { return symbol(sym.FUNCTION);
          }
        case 128: break;
        case 41: 
          { string.append( '\\' );
          }
        case 129: break;
        case 3: 
          { return symbol(sym.ID, yytext());
          }
        case 130: break;
        case 68: 
          { return symbol(sym.READLN);
          }
        case 131: break;
        case 47: 
          { return symbol(sym.CHAR_LITERAL, new Character(yytext().charAt(1)));
          }
        case 132: break;
        case 6: 
          { /* just skip what was found, do nothing */
          }
        case 133: break;
        case 55: 
          { return symbol(sym.CHAR);
          }
        case 134: break;
        case 48: 
          { return symbol(sym.REF);
          }
        case 135: break;
        case 18: 
          { return symbol(sym.RBRACKET);
          }
        case 136: break;
        case 64: 
          { return symbol(sym.CONST);
          }
        case 137: break;
        case 43: 
          { string.append( '\f' );
          }
        case 138: break;
        case 10: 
          { return symbol(sym.DIVIDE);
          }
        case 139: break;
        case 60: 
          { return symbol(sym.BOOL);
          }
        case 140: break;
        case 29: 
          { /* ignore */
          }
        case 141: break;
        case 2: 
          { throw new Error("Illegal character <"+yytext()+">");
          }
        case 142: break;
        case 31: 
          { return symbol(sym.GREATER_THAN_OR_EQUAL);
          }
        case 143: break;
        case 24: 
          { string.append( yytext() );
          }
        case 144: break;
        case 38: 
          { return symbol(sym.DO);
          }
        case 145: break;
        case 50: 
          { return symbol(sym.FOR);
          }
        case 146: break;
        case 54: 
          { return symbol(sym.CASE);
          }
        case 147: break;
        case 28: 
          { return symbol(sym.FLOAT_LITERAL, new Float(yytext()));
          }
        case 148: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
