
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 06 03:05:06 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int STRING_LITERAL = 54;
  public static final int FUNCTION = 23;
  public static final int LBRACKET = 10;
  public static final int CASE = 25;
  public static final int GREATER = 14;
  public static final int SEMI = 4;
  public static final int REPEAT = 30;
  public static final int INT = 47;
  public static final int ARRAY = 45;
  public static final int REF = 40;
  public static final int LESS = 16;
  public static final int FOR = 29;
  public static final int MINUS = 6;
  public static final int WRITE = 42;
  public static final int GREATER_THAN = 15;
  public static final int AND = 38;
  public static final int SEMICOLON = 2;
  public static final int TYPE = 50;
  public static final int OR = 39;
  public static final int BOOL = 49;
  public static final int BEGIN = 36;
  public static final int UNTIL = 35;
  public static final int PLUS = 5;
  public static final int WRITELN = 41;
  public static final int ASSIGN = 21;
  public static final int IF = 26;
  public static final int ID = 53;
  public static final int DOT = 20;
  public static final int DOTS = 19;
  public static final int OF = 34;
  public static final int EOF = 0;
  public static final int RBRACKET = 11;
  public static final int EQUAL = 18;
  public static final int error = 1;
  public static final int PROGRAM = 22;
  public static final int NUMBER = 52;
  public static final int MOD = 9;
  public static final int READLN = 43;
  public static final int REAL = 48;
  public static final int TIMES = 7;
  public static final int COLON = 3;
  public static final int LBRACE = 12;
  public static final int ELSE = 27;
  public static final int READ = 44;
  public static final int TO = 32;
  public static final int WHILE = 28;
  public static final int THEN = 31;
  public static final int RBRACE = 13;
  public static final int END = 37;
  public static final int STRING = 46;
  public static final int DOWNTO = 51;
  public static final int LESS_THAN = 17;
  public static final int VAR = 24;
  public static final int DO = 33;
}

