
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 02 13:51:59 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int STRING_LITERAL = 56;
  public static final int FUNCTION = 23;
  public static final int LBRACKET = 10;
  public static final int CHAR = 52;
  public static final int CONST = 48;
  public static final int CHAR_LITERAL = 59;
  public static final int LESS_THAN_OR_EQUAL = 17;
  public static final int CASE = 25;
  public static final int NOT_EQUAL = 19;
  public static final int SEMI = 4;
  public static final int REPEAT = 30;
  public static final int INT = 45;
  public static final int ARRAY = 43;
  public static final int REF = 40;
  public static final int FOR = 29;
  public static final int MINUS = 6;
  public static final int GREATER_THAN = 14;
  public static final int BOOLEAN_LITERAL = 57;
  public static final int NOT = 49;
  public static final int AND = 38;
  public static final int SEMICOLON = 2;
  public static final int RECORD = 53;
  public static final int RPAR = 13;
  public static final int TYPE = 47;
  public static final int OR = 39;
  public static final int BOOL = 46;
  public static final int BEGIN = 36;
  public static final int UNTIL = 35;
  public static final int PLUS = 5;
  public static final int WRITELN = 41;
  public static final int ASSIGN = 21;
  public static final int IF = 26;
  public static final int ID = 55;
  public static final int DOT = 20;
  public static final int OF = 34;
  public static final int EOF = 0;
  public static final int RBRACKET = 11;
  public static final int EQUAL = 18;
  public static final int error = 1;
  public static final int PROGRAM = 22;
  public static final int MOD = 9;
  public static final int VOID = 51;
  public static final int READLN = 42;
  public static final int TIMES = 7;
  public static final int COLON = 3;
  public static final int ELSE = 27;
  public static final int TO = 32;
  public static final int WHILE = 28;
  public static final int FLOAT = 50;
  public static final int THEN = 31;
  public static final int END = 37;
  public static final int STRING = 44;
  public static final int LPAR = 12;
  public static final int GREATER_THAN_OR_EQUAL = 15;
  public static final int FLOAT_LITERAL = 58;
  public static final int LESS_THAN = 16;
  public static final int VAR = 24;
  public static final int DO = 33;
  public static final int INT_LITERAL = 54;
}

